apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
type: Opaque
stringData:
  admin.password: $2a$10$9MCAX3o6EOIrXxkGAKK4qOUB3hN8ywx9LI61NQX7eq09D7Ijz4uqu%
  admin.passwordMtime: 2024-02-10T13:38:38KST