apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
type: Opaque
stringData:
  admin.password: $2a$10$sy85UCWBUJrydPbwxAf6X.kf942ePsPCqhSxoIZ4fP6l9FIHX8pA.
  admin.passwordMtime: 2024-02-14T23:14:17KST
  server.secretkey: ZKhDVhWH0hh3E/7JZm+nYZE0FoowFnkgUiwLzjk9cUs=